[Metadata]
Name = "Zip Upscaler's Test and Benchmmark"
Description = """
Package upscaler's test and benchmark component into a single .zip package.
"""
Type = 'manual'




[Variables]
Product = 'upscaler-tests'

[FMTVariables]
PackageDir = '{{- .WorkingDir -}}/{{- .Product -}}'




[[Dependencies]]
Name = 'Zip Program for Archive and Compression'
Conditions = 'all-all'
Type = 'command'
Command = 'zip'


[[Dependencies]]
Name = 'GPG Program for Cryptography Certificate Generation'
Conditions = 'all-all'
Type = 'command'
Command = 'gpg'




[Packages.001]
OS = [ 'all' ]
Arch = [ 'all' ]
Name = '{{- .Product -}}-{{- .PkgVersion -}}'
Distribution = [
	'stable',
]
BuildSource = false

[Packages.001.Files]
'{{- .PackageDir -}}/start.cmd' = '{{- .RootDir -}}/start.cmd'




[[CMD]]
Name = 'Delete Existing Packaging Directory if Exists'
Type = 'delete-recursive-quiet'
Condition = [ 'all-all' ]
Source = '{{ .PackageDir -}}'


[[CMD]]
Name = 'Make Packaging Directory for New Packaging Job'
Type = 'create-path'
Condition = [ 'all-all' ]
Source = '{{ .PackageDir -}}'


[[CMD]]
Name = 'Create tests/ directory'
Type = 'create-dir'
Condition = [ 'all-all' ]
Source = '{{- .PackageDir -}}/tests'


[[CMD]]
Name = 'Create tests/image directory'
Type = 'create-dir'
Condition = [ 'all-all' ]
Source = '{{- .PackageDir -}}/tests/image'


[[CMD]]
Name = 'Create tests/video directory'
Type = 'create-dir'
Condition = [ 'all-all' ]
Source = '{{- .PackageDir -}}/tests/video'


[[CMD]]
Name = 'Copy tests/benchmark.cmd to target'
Type = 'copy'
Condition = [ 'all-all' ]
Source = '{{- .RootDir -}}/tests/benchmark.cmd'
Target = '{{- .PackageDir -}}/tests/benchmark.cmd'


[[CMD]]
Name = 'Copy tests/image/sample-01.jpeg to target'
Type = 'copy'
Condition = [ 'all-all' ]
Source = '{{- .RootDir -}}/tests/image/sample-01.jpeg'
Target = '{{- .PackageDir -}}/tests/image/sample-01.jpeg'


[[CMD]]
Name = 'Copy tests/image/sample-1-640x360.mp4 to target'
Type = 'copy'
Condition = [ 'all-all' ]
Source = '{{- .RootDir -}}/tests/video/sample-1-640x360.mp4'
Target = '{{- .PackageDir -}}/tests/video/sample-1-640x360.mp4'


[[CMD]]
Name = 'Copy VERSION to target'
Type = 'copy'
Condition = [ 'all-all' ]
Source = '{{- .RootDir -}}/VERSION'
Target = '{{- .PackageDir -}}/VERSION'


[[CMD]]
Name = 'Copy LICENSE.TXT to target'
Type = 'copy'
Condition = [ 'all-all' ]
Source = '{{- .RootDir -}}/LICENSE.txt'
Target = '{{- .PackageDir -}}/LICENSE.txt'


[[CMD]]
Name = 'Compress into Zip'
Type = 'command'
Condition = [ 'all-all' ]
Location = '{{- .WorkingDir -}}'
Source = 'zip -r "{{- .Product -}}-{{- .App.Version -}}.zip" "{{- .Product -}}"'


[[CMD]]
Name = 'Generate GPG Certificate'
Type = 'command'
Condition = [ 'all-all' ]
Location = '{{- .WorkingDir -}}'
Source = '''gpg \
--batch --yes \
--local-user hollowaykeanho@gmail.com \
--armor \
--detach-sign \
"{{- .Product -}}-{{- .App.Version -}}.zip" \
'''
